export const productData = [
    { id:1, image: "/i1.png", code: "Just In", name: "Nike Air Force 1 Mid '07", color: "1 Colour", price: "MRP: ₹ 10,695.00", category: "Mens Shoes", quantity:"1", description: "The Nike Air Force 1 Mid '07 is a reimagining of the iconic Air Force 1, first introduced in 1982. This model features a mid-top silhouette that offers added ankle support, making it ideal for those who need extra stability while on the move. Crafted from premium leather, the Air Force 1 Mid '07 offers both style and durability, making it perfect for everyday wear. The classic design, paired with modern touches, ensures these sneakers are not only a nod to heritage but also a versatile piece for contemporary fashion. The adjustable ankle strap adds to the customization, allowing you to wear them in your own unique style." },

    { id:2, image: "/i2.png", code: "Just In", name: "Nike Court Vision Low Next Nature", price: "MRP: ₹ 4,995.00", category: "Mens Shoes", color: "1 Colour", quantity:"1", description: "The Nike Court Vision Low Next Nature combines classic basketball-inspired styling with innovative sustainability. Constructed with at least 20% recycled content, this sneaker is part of Nikes commitment to reducing environmental impact without sacrificing style. The low-profile design is sleek and minimal, with subtle details that make it perfect for everyday wear. Featuring a leather and synthetic upper, this shoe delivers durability while maintaining a lightweight feel. Whether youre running errands or heading to the gym, these shoes provide both comfort and style. The clean lines and neutral colorways ensure that the Court Vision Low Next Nature can be easily paired with a variety of outfits, from athletic wear to casual streetwear." },

    { id:3, image: "/i3.png", code: "Just In", name: "Nike Air Force 1 PLATFORM", price: "MRP: ₹ 8,695.00", category: "Womens Shoes", color: "1 Colour", quantity:"1", description: "The Nike Air Force 1 PLATFORM adds a bold twist to the classic Air Force 1 silhouette by featuring an elevated sole that adds height and style. This sneaker keeps all the elements of the original, like the iconic round toe and sleek leather upper, but with a modern, platform sole for a more fashion-forward look. Perfect for those who love to stand out, the Air Force 1 PLATFORM offers the same durability and comfort that the Air Force 1 is known for, but with the added benefit of extra height and a more contemporary design. The rubber outsole ensures grip and traction, while the padded collar and cushioned midsole offer superior comfort. These shoes are ideal for anyone who wants to make a statement with their footwear, whether youre headed out for a casual outing or looking to elevate your everyday look." },

    { id:4, image: "/i4.png", code: "Just In", name: "Nike Air Force 1 React", price: "MRP: ₹ 13,295.00", category: "Mens Shoes", color: "1 Colour",quantity:"1", description: "The Nike Air Force 1 React combines the timeless design of the Air Force 1 with advanced React foam technology for added comfort and performance. The React foam midsole delivers a soft, responsive feel with each step, making these sneakers perfect for those who need cushioning and support throughout the day. Whether you're running errands, going for a walk, or simply hanging out, these sneakers will keep your feet feeling fresh and comfortable. The combination of leather and synthetic materials in the upper offers durability and a stylish aesthetic, while the signature Air Force 1 features, including the perforated toe box and iconic logo, remain intact." },

    { id:5, image: "/i5.png", code: "Promo Exclusion", name: "Air Jordan 1 Elevate Low", price: "MRP: ₹ 11,895.00", category: "Womens Shoes", color: "1 Colour",quantity:"1", description: "The Air Jordan 1 Elevate Low brings a fresh twist to the classic Air Jordan 1 silhouette. Designed for a more casual look, these low-top sneakers feature a durable leather upper and an elevated platform sole for added height and comfort. The Jordan 1 Elevate Low takes the timeless Jordan 1 aesthetic and gives it a modern, fashion-forward update with the platform sole, which not only provides a height boost but also ensures comfort for all-day wear. The retro-inspired colorways give a nod to the original Jordan 1 while maintaining a contemporary feel. Whether you're heading to the gym, hanging out with friends, or going for a quick walk, these sneakers offer both style and functionality." },

    { id:6, image: "/i6.png", code: "Just In", name: "Nike Standard Issue", price: "MRP: ₹ 2,895.00", category: "Mens Basketball Jersey", color: "1 Colour",quantity:"1", description: "The Nike Standard Issue Mens Basketball Jersey is designed with the athlete in mind, offering a lightweight and breathable fit thats perfect for high-performance activities. Made with Nikes Dri-FIT technology, this jersey wicks away sweat and keeps you cool during intense training sessions or games. The loose fit allows for full range of motion, making it ideal for sports where mobility is key. Featuring a clean, minimalist design with the iconic Nike logo, this jersey pairs well with any athletic wear and can easily transition from the court to casual streetwear. Whether youre playing basketball, working out, or just running errands, the Nike Standard Issue jersey will keep you comfortable and stylish. " },

    { id:7, image: "/i7.png", code: "Promo Exclusion", name: "Nike Dunk Low Retro SE", price: "MRP: ₹ 9,695.00", category: "Mens Shoes", color: "1 Colour",quantity:"1", description: "The Nike Dunk Low Retro SE is a modern take on a classic basketball shoe thats known for its versatility and comfort. With a retro-inspired design, the Dunk Low Retro SE combines premium leather and suede uppers for a stylish, textured look. The low-top cut offers a sleek and minimalist design that pairs well with a variety of outfits, making it perfect for casual wear or as part of a laid-back athletic ensemble. The cushioned insole and flexible midsole provide support and comfort, while the rubber outsole ensures superior traction, making these sneakers both stylish and functional."},

    { id:8, image: "/i8.png", code:"Sustainable Materials", name: "Nike Dri-FIT UV Hyverse", price: "MRP: ₹ 2,495.00", category: "Mens Short-Sleeve Graphic Fitness Top", color: "1 Colour", quantity:"1", description: "The Nike Dri-FIT UV Hyverse is the ultimate workout shirt designed for athletes who demand performance. Made from lightweight, breathable fabric, this shirt offers superior moisture-wicking properties, keeping you cool and dry during intense workouts. The Dri-FIT UV technology provides extra protection from the suns harmful rays, making it perfect for outdoor activities. Whether you're hitting the gym, going for a run, or playing sports outside, this shirt offers both functionality and style. The relaxed fit ensures freedom of movement, while the bold graphic design adds a touch of modern flair." },

    { id:9, image: "/i9.png", code: "Just In", name: "Nike Court Vision Low", price: "MRP: ₹ 5,695.00", category: "Mens Shoes", color: "1 Colour", quantity:"1", description: "The Nike Court Vision Low is a sleek, low-profile sneaker that combines retro-inspired styling with modern comfort. Perfect for casual wear, the Court Vision Low features a clean, minimalist design that pairs well with everything from athletic wear to everyday streetwear. The leather and synthetic upper provides durability, while the padded insole ensures comfort for all-day wear. The rubber outsole delivers reliable traction, making these sneakers perfect for both indoor and outdoor activities. Whether you're heading to class, running errands, or just hanging out, the Nike Court Vision Low offers the perfect combination of style and function." },

    { id:10, image: "/i10.png", code: "Just In", name: "Nike Dri-FIT Ready", price: "MRP: ₹ 2,495.00", category: "Mens Short-Sleeve Fitness Top", color: "3 Colour", quantity:"1", description: "The Nike Dri-FIT Ready is a versatile fitness top that is ideal for high-intensity workouts. Made with Dri-FIT technology, this top pulls sweat away from your skin, ensuring that you stay cool and dry even during the most strenuous exercises. The lightweight, stretchy fabric allows for unrestricted movement, making it perfect for activities like running, yoga, or weight training. The sleek design and breathable material also make it great for casual wear or lounging around. With its modern fit and stylish appearance, the Nike Dri-FIT Ready top is a must-have for anyone who values both comfort and style in their activewear. Whether you're working out or just relaxing, this top offers all-day comfort and support." },

    { id:11, image: "/i11.png", code: "Just In", name: "Nike One Leak Protection: Period", price: "MRP: ₹ 3,395.00", category: "Womens Mid-Rise 18cm (approx.) Biker Shorts", color: "2 Colour", quantity:"1", description: "The Nike One Leak Protection: Period is a revolutionary product designed specifically for women who need reliable protection and comfort during their period. These mid-rise biker shorts are made with a unique, absorbent fabric that provides maximum leak protection, so you can feel confident and secure throughout the day. Featuring Nikes signature Dri-FIT technology, these shorts wick away sweat and moisture, keeping you dry and comfortable during exercise or everyday activities. The fabric is soft, stretchy, and breathable, offering a snug fit that moves with your body, providing support and comfort wherever you go. The 18cm inseam length provides a comfortable fit, while the anti-odor technology ensures you stay fresh all day long." },

    { id:12, image: "/i12.png", code: "Just In", name: "Nike Air Force 1 LV8 3", price: "MRP: ₹ 7,495.00", category: "Older Kids Shoe", color: "1 Colour", quantity:"1", description: "The Nike Air Force 1 LV8 3 combines the iconic look of the classic Air Force 1 with modern style and enhanced comfort. These shoes are crafted with premium materials that not only ensure durability but also elevate the sneakers appearance with bold accents and textures. Featuring a high-quality leather upper, these shoes offer a sleek, smooth look thats both stylish and easy to maintain. The classic Nike Air cushioning system delivers a responsive, comfortable ride with every step, making them perfect for all-day wear. The low-cut design provides a versatile look that pairs easily with various outfits, whether you're dressing up for a casual day out or down for a more laid-back vibe. The Air Force 1 LV8 3 is equipped with a sturdy rubber outsole that provides excellent traction and grip, ensuring stability no matter the surface. " },

    { id:13, image: "/i13.png", code: "Just In", name: "Nike Air Max SYSTM", price: "MRP: ₹ 6,495.00", category: "Older Kids Shoe", color: "1 Colour",quantity:"1", description: " The Nike Air Max SYSTM blends retro style with modern comfort, offering a sleek design for active kids. With a durable synthetic and leather upper, these shoes are built to last, while the Air Max cushioning ensures a soft, responsive ride. The classic Max Air unit provides all-day comfort, making these shoes perfect for everyday adventures, whether running or playing. The breathable upper keeps feet cool, while the rubber outsole delivers reliable traction for various surfaces." },

    { id:14, image: "/i14.png", code: "Just In", name: "Nike Alate All U", price: "MRP: ₹ 2,195.00", category: "Womens Light-Support Lightly Lined U-Neck Printed Sports Bra", color: "1 Colour", quantity:"1", description: " The Nike Alate All U Sports Bra is designed for light support with a focus on comfort and style. Crafted from soft, stretchy fabric, this lightly lined sports bra offers a snug fit that moves with you. The U-neck design adds a flattering silhouette, while the bold prints give it a fashionable touch. Perfect for low-impact activities or lounging, the bras moisture-wicking material ensures you stay dry and comfortable all day long." },

    { id:15, image: "/i15.png", code: "Just In", name: "Nike Court Legacy Lift", price: "MRP: ₹ 7,495.00", category: "Older Kid's Shoe", color: "2 Colour", quantity:"1", description: "The Nike Court Legacy Lift offers a perfect blend of classic tennis style and contemporary performance. Featuring a durable leather upper with a retro design, these shoes provide a clean, versatile look. The cushioned insole ensures comfort during long hours of wear, while the rubber outsole provides excellent grip and stability. The elevated design adds a fresh twist to the traditional tennis shoe, making it a stylish choice for young athletes or casual wear." },

    { id:16, image: "/i16.png", code: "Just In", name: "Nike Swaoosh", price: "MRP: ₹ 7,495.00", category: "Women's Medium-support Padded Sports Bra Tank", color: "2 Colour", quantity:"1", description: " The Nike Swaoosh Sports Bra Tank is designed for medium support, making it ideal for active women who need both performance and style. The padded bra offers enhanced comfort, while the tank design provides added ventilation and a flattering fit. Crafted from breathable fabric, this sports bra tank wicks away moisture to keep you dry during your workouts. The stylish Nike swoosh detail adds a bold touch, making it a perfect piece for both sports and casual wear." },



  ];